name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Allow Composer Plugins ✅
        run: composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install PHP_CodeSniffer
        run: composer global require squizlabs/php_codesniffer wp-coding-standards/wpcs

      - name: Auto-fix PHPCS issues ✅
        run: composer global exec phpcbf -- --standard=WordPress --ignore=vendor .

      - name: Run PHPCS
        run: phpcs --standard=WordPress --ignore=vendor .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Verify PHP Version ✅
        run: php -v  # ✅ Print PHP version to logs

      - name: Update Composer Dependencies ✅
        run: composer update --no-dev --prefer-dist --no-interaction

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Fix PHPUnit Permissions ✅
        run: chmod +x vendor/bin/phpunit  # ✅ Allow execution of PHPUnit

      - name: Run PHPUnit
        run: vendor/bin/phpunit
