name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: php-cs-fixer, phpcs, phpcbf

      - name: Install WordPress Coding Standards (WPCS)
        run: |
          composer global require "wp-coding-standards/wpcs"
          phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
          phpcs -i

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPCS (Strict Mode)
        run: phpcs --standard=WordPress --ignore=vendor .

      - name: Auto-fix PHPCS issues
        run: phpcbf --standard=WordPress --ignore=vendor . || true

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7  # ✅ Use MySQL 5.7
        env:
          MYSQL_ROOT_PASSWORD: root  # ✅ Correctly set root password
          MYSQL_DATABASE: wordpress_test  # ✅ Database for WordPress tests
          MYSQL_USER: wordpress  # ✅ Create a non-root MySQL user
          MYSQL_PASSWORD: wordpress  # ✅ Set password for the user
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install Dependencies
        run: composer install

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Start WordPress
        run: |
          wp core download --allow-root
          wp config create --dbname=wordpress_test --dbuser=wordpress --dbpass=wordpress --dbhost=127.0.0.1 --allow-root
          wp db query "DROP DATABASE IF EXISTS wordpress_test;" --allow-root || true
          wp db create --allow-root
          wp core install --url=localhost --title="Test Site" --admin_user=admin --admin_password=admin --admin_email=test@example.com --allow-root
          echo "WordPress Installed"

      - name: Verify WordPress is Installed
        run: wp core is-installed --allow-root || exit 1  # ✅ Debugging step

      - name: Run PHPUnit
        run: |
          chmod +x vendor/bin/phpunit  # ✅ Fix: Grant execute permission
          vendor/bin/phpunit --testdox

