name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPCS (Strict Mode ❌)
        run: vendor/bin/phpcs --standard=WordPress --ignore=vendor .

      - name: Auto-fix PHPCS issues ✅
        run: vendor/bin/phpcbf --standard=WordPress --ignore=vendor . || true

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install Dependencies
        run: composer install

      - name: Start WordPress
        run: |
          wp core download --allow-root
          wp config create --dbname=wordpress_test --dbuser=root --dbpass=root --dbhost=127.0.0.1 --allow-root
          wp db create --allow-root
          wp core install --url=localhost --title="Test Site" --admin_user=admin --admin_password=admin --admin_email=test@example.com --allow-root

      - name: Run PHPUnit
        run: vendor/bin/phpunit --testdox
